language: node_js
sudo: false
node_js:
    - 0.12
    - 4.1.0
env:
  - COVERALLS=1
git:
  depth: 10
before_install:
  - 'npm config set loglevel error'
services:
  - elasticsearch
before_script:
  - sleep 10
after_success: 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
