language: node_js
sudo: false
node_js:
    - "6"
env:
  - COVERALLS=1
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
git:
  depth: 10
before_install:
  - 'npm config set loglevel error'
services:
  - elasticsearch
before_script:
  - sleep 10
after_success:
  - 'npm run coveralls'
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
