language: node_js
sudo: false
node_js:
  - "6"
env:
  global:
    - COVERALLS=1
    - WAIT_FOR_ES=1
  matrix:
    - ES_VERSION=5.0.1
install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch --daemonize --path.data /tmp
  - npm install
git:
  depth: 10
before_install:
  - 'npm config set loglevel error'
before_script:
  - sleep 10
after_success:
  - 'npm run coveralls'
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
